### ISSUE TITLE
docker version of the sidecar v13 is not accessible.

### ISSUE THREAD

**Issue by benxiao** [paritytech/substrate-api-sidecar#1065]
**Description**

docker version of the sidecar from v13.0 is not accessible.

**Steps to Reproduce**

```
version: "3.8"
services:
  kusama:
    container_name: kusama
    image: docker.io/parity/polkadot:v0.9.29
    restart: unless-stopped
    command: '--chain kusama --unsafe-ws-external --unsafe-rpc-external --rpc-cors=all --pruning archive'

  sidecar:
    depends_on:
      - kusama
    container_name: kusama-sidecar
    image: docker.io/parity/substrate-api-sidecar:v13.1.0
    restart: unless-stopped
    read_only: true
    ports:
            - "8082:8080"
    environment:
      SAS_SUBSTRATE_WS_URL: ws://kusama:9944
```

run docker-compose up -d on this docker-compose.yml

cannot access localhost:8082

if i set the version to v12.4.3, the server would be accessible.
